# Makefile.in generated by automake 1.10 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Copyright (C) Tildeslash Ltd. All rights reserved.


pkgdatadir = $(datadir)/monit
pkglibdir = $(libdir)/monit
pkgincludedir = $(includedir)/monit
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i386-apple-darwin10.8.0
host_triplet = i386-apple-darwin10.8.0
bin_PROGRAMS = monit$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(top_srcdir)/configure \
	$(top_srcdir)/src/config.h.in AUTHORS COPYING \
	config/config.guess config/config.sub config/install-sh \
	config/ltmain.sh config/missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/src/config.h
CONFIG_CLEAN_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_monit_OBJECTS = src/y.tab.$(OBJEXT) src/lex.yy.$(OBJEXT) \
	src/monit.$(OBJEXT) src/alert.$(OBJEXT) \
	src/collector.$(OBJEXT) src/control.$(OBJEXT) \
	src/daemonize.$(OBJEXT) src/env.$(OBJEXT) src/event.$(OBJEXT) \
	src/file.$(OBJEXT) src/gc.$(OBJEXT) src/http.$(OBJEXT) \
	src/log.$(OBJEXT) src/md5.$(OBJEXT) src/net.$(OBJEXT) \
	src/process.$(OBJEXT) src/sendmail.$(OBJEXT) src/sha.$(OBJEXT) \
	src/signal.$(OBJEXT) src/socket.$(OBJEXT) src/spawn.$(OBJEXT) \
	src/ssl.$(OBJEXT) src/state.$(OBJEXT) src/status.$(OBJEXT) \
	src/util.$(OBJEXT) src/validate.$(OBJEXT) \
	src/xmalloc.$(OBJEXT) src/xml.$(OBJEXT) \
	src/http/base64.$(OBJEXT) src/http/cervlet.$(OBJEXT) \
	src/http/engine.$(OBJEXT) src/http/processor.$(OBJEXT) \
	src/protocols/apache_status.$(OBJEXT) \
	src/protocols/clamav.$(OBJEXT) src/protocols/default.$(OBJEXT) \
	src/protocols/dns.$(OBJEXT) src/protocols/dwp.$(OBJEXT) \
	src/protocols/ftp.$(OBJEXT) src/protocols/generic.$(OBJEXT) \
	src/protocols/gps.$(OBJEXT) src/protocols/http.$(OBJEXT) \
	src/protocols/imap.$(OBJEXT) src/protocols/ldap2.$(OBJEXT) \
	src/protocols/ldap3.$(OBJEXT) src/protocols/lmtp.$(OBJEXT) \
	src/protocols/memcache.$(OBJEXT) src/protocols/mysql.$(OBJEXT) \
	src/protocols/nntp.$(OBJEXT) src/protocols/ntp3.$(OBJEXT) \
	src/protocols/pgsql.$(OBJEXT) src/protocols/pop.$(OBJEXT) \
	src/protocols/postfix_policy.$(OBJEXT) \
	src/protocols/protocol.$(OBJEXT) \
	src/protocols/radius.$(OBJEXT) src/protocols/rdate.$(OBJEXT) \
	src/protocols/rsync.$(OBJEXT) src/protocols/sip.$(OBJEXT) \
	src/protocols/smtp.$(OBJEXT) src/protocols/ssh.$(OBJEXT) \
	src/protocols/tns.$(OBJEXT) src/device/device_common.$(OBJEXT) \
	src/device/sysdep_DARWIN.$(OBJEXT) \
	src/process/process_common.$(OBJEXT) \
	src/process/sysdep_DARWIN.$(OBJEXT)
monit_OBJECTS = $(am_monit_OBJECTS)
monit_LDADD = $(LDADD)
monit_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(monit_LDFLAGS) \
	$(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I. -I$(top_builddir)/src
depcomp =
am__depfiles_maybe =
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(monit_SOURCES)
DIST_SOURCES = $(monit_SOURCES)
man1dir = $(mandir)/man1
NROFF = nroff
MANS = $(man_MANS)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Users/aforward/tp/projects/monit_svn/config/missing --run aclocal-1.10
AMTAR = ${SHELL} /Users/aforward/tp/projects/monit_svn/config/missing --run tar
AR = ar
ARCH = DARWIN
AUTOCONF = ${SHELL} /Users/aforward/tp/projects/monit_svn/config/missing --run autoconf
AUTOHEADER = ${SHELL} /Users/aforward/tp/projects/monit_svn/config/missing --run autoheader
AUTOMAKE = ${SHELL} /Users/aforward/tp/projects/monit_svn/config/missing --run automake-1.10
AWK = awk
CC = gcc
CCDEPMODE = depmode=none
CFLAGS = -Wno-address -Wno-pointer-sign -g -O2 -Wall -Wunused -Wno-unused-label -funsigned-char -D_GNU_SOURCE -std=c99 -DREENTRANT -no-cpp-precomp -DNEED_SOCKLEN_T_DEFINED
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DSYMUTIL = dsymutil
DUMPBIN = 
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
FGREP = /usr/bin/grep -F
FLEX = /opt/local/bin/flex
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/libexec/gcc/i686-apple-darwin10/4.2.1/ld
LDFLAGS = 
LIBOBJS =  ${LIBOBJDIR}error$U.o ${LIBOBJDIR}lstat$U.o
LIBS = -lpam -lpthread -lresolv  -framework System -multiply_defined suppress -lssl -lcrypto
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = lipo
LN_S = ln -s
LTLIBOBJS =  ${LIBOBJDIR}error$U.lo ${LIBOBJDIR}lstat$U.lo
MAKEINFO = ${SHELL} /Users/aforward/tp/projects/monit_svn/config/missing --run makeinfo
MKDIR_P = config/install-sh -c -d
NM = /usr/bin/nm
NMEDIT = nmedit
OBJEXT = o
OTOOL = otool
OTOOL64 = :
PACKAGE = monit
PACKAGE_BUGREPORT = monit-general@nongnu.org
PACKAGE_NAME = monit
PACKAGE_STRING = monit 5.2.7
PACKAGE_TARNAME = monit
PACKAGE_VERSION = 5.2.7
PATH_SEPARATOR = :
POD2MAN = /opt/local/bin/pod2man
POD2MANFLAGS = --center 'User Commands' --release 'July 26. 2011' --date='www.mmonit.com' --lax
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 5.2.7
YACC = bison -y
abs_builddir = /Users/aforward/tp/projects/monit_svn
abs_srcdir = /Users/aforward/tp/projects/monit_svn
abs_top_builddir = /Users/aforward/tp/projects/monit_svn
abs_top_srcdir = /Users/aforward/tp/projects/monit_svn
ac_ct_CC = gcc
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i386-apple-darwin10.8.0
build_alias = 
build_cpu = i386
build_os = darwin10.8.0
build_vendor = apple
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i386-apple-darwin10.8.0
host_alias = 
host_cpu = i386
host_os = darwin10.8.0
host_vendor = apple
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = $(SHELL) /Users/aforward/tp/projects/monit_svn/config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
lt_ECHO = /bin/echo
mandir = ${datarootdir}/man
mkdir_p = $(top_builddir)/config/install-sh -c -d
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sslincldir = /usr/include
ssllibdir = /usr/lib
sysconfdir = ${prefix}/etc
target_alias = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = foreign no-dependencies subdir-objects
ACLOCAL_AMFLAGS = -I m4
EXTRA_DIST = README AUTHORS CHANGES COPYING bootstrap doc src config monitrc contrib monit.1
FLEXFLAGS = -i
YACCFLAGS = -dvt
AM_CPPFLAGS = $(CPPFLAGS) $(EXTCPPFLAGS) -DDARWIN -DSYSCONFDIR="\"${prefix}/etc\""
AM_LDFLAGS = $(LDFLAGS) $(EXTLDFLAGS) -L./lib/
INCLUDES = -I./src -I./src/device -I./src/http -I./src/process -I./src/protocols 
monit_SOURCES = src/y.tab.c \
		  src/lex.yy.c \
		  src/monit.c \
		  src/alert.c \
		  src/collector.c \
		  src/control.c \
		  src/daemonize.c \
		  src/env.c \
		  src/event.c \
		  src/file.c \
		  src/gc.c \
		  src/http.c \
		  src/log.c \
		  src/md5.c \
		  src/net.c \
		  src/process.c \
		  src/sendmail.c \
		  src/sha.c \
		  src/signal.c \
		  src/socket.c \
		  src/spawn.c \
		  src/ssl.c \
		  src/state.c \
		  src/status.c \
		  src/util.c \
		  src/validate.c \
		  src/xmalloc.c \
		  src/xml.c \
		  src/http/base64.c \
		  src/http/cervlet.c \
		  src/http/engine.c \
		  src/http/processor.c \
		  src/protocols/apache_status.c \
		  src/protocols/clamav.c \
		  src/protocols/default.c \
		  src/protocols/dns.c \
		  src/protocols/dwp.c \
		  src/protocols/ftp.c \
		  src/protocols/generic.c \
		  src/protocols/gps.c \
		  src/protocols/http.c \
		  src/protocols/imap.c \
		  src/protocols/ldap2.c \
		  src/protocols/ldap3.c \
		  src/protocols/lmtp.c \
		  src/protocols/memcache.c \
		  src/protocols/mysql.c \
		  src/protocols/nntp.c \
		  src/protocols/ntp3.c \
		  src/protocols/pgsql.c \
		  src/protocols/pop.c \
		  src/protocols/postfix_policy.c \
		  src/protocols/protocol.c \
		  src/protocols/radius.c \
		  src/protocols/rdate.c \
		  src/protocols/rsync.c \
		  src/protocols/sip.c \
		  src/protocols/smtp.c \
		  src/protocols/ssh.c \
		  src/protocols/tns.c \
		  src/device/device_common.c \
		  src/device/sysdep_DARWIN.c \
		  src/process/process_common.c \
		  src/process/sysdep_DARWIN.c

monit_LDFLAGS = -static $(EXTLDFLAGS)
man_MANS = monit.1
BUILT_SOURCES = src/lex.yy.c src/y.tab.c src/tokens.h
CLEANFILES = $(BUILT_SOURCES)
DISTCLEANFILES = *~ 
all: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign '; \
	      cd $(srcdir) && $(AUTOMAKE) --foreign  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --foreign  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)

src/config.h: src/stamp-h1
	@if test ! -f $@; then \
	  rm -f src/stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) src/stamp-h1; \
	else :; fi

src/stamp-h1: $(top_srcdir)/src/config.h.in $(top_builddir)/config.status
	@rm -f src/stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status src/config.h
$(top_srcdir)/src/config.h.in:  $(am__configure_deps) 
	cd $(top_srcdir) && $(AUTOHEADER)
	rm -f src/stamp-h1
	touch $@

distclean-hdr:
	-rm -f src/config.h src/stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	     || test -f $$p1 \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) --mode=install $(binPROGRAMS_INSTALL) '$$p' '$(DESTDIR)$(bindir)/$$f'"; \
	   $(INSTALL_PROGRAM_ENV) $(LIBTOOL) --mode=install $(binPROGRAMS_INSTALL) "$$p" "$(DESTDIR)$(bindir)/$$f" || exit 1; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f '$(DESTDIR)$(bindir)/$$f'"; \
	  rm -f "$(DESTDIR)$(bindir)/$$f"; \
	done

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  echo " rm -f $$p $$f"; \
	  rm -f $$p $$f ; \
	done
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/y.tab.$(OBJEXT): src/$(am__dirstamp)
src/lex.yy.$(OBJEXT): src/$(am__dirstamp)
src/monit.$(OBJEXT): src/$(am__dirstamp)
src/alert.$(OBJEXT): src/$(am__dirstamp)
src/collector.$(OBJEXT): src/$(am__dirstamp)
src/control.$(OBJEXT): src/$(am__dirstamp)
src/daemonize.$(OBJEXT): src/$(am__dirstamp)
src/env.$(OBJEXT): src/$(am__dirstamp)
src/event.$(OBJEXT): src/$(am__dirstamp)
src/file.$(OBJEXT): src/$(am__dirstamp)
src/gc.$(OBJEXT): src/$(am__dirstamp)
src/http.$(OBJEXT): src/$(am__dirstamp)
src/log.$(OBJEXT): src/$(am__dirstamp)
src/md5.$(OBJEXT): src/$(am__dirstamp)
src/net.$(OBJEXT): src/$(am__dirstamp)
src/process.$(OBJEXT): src/$(am__dirstamp)
src/sendmail.$(OBJEXT): src/$(am__dirstamp)
src/sha.$(OBJEXT): src/$(am__dirstamp)
src/signal.$(OBJEXT): src/$(am__dirstamp)
src/socket.$(OBJEXT): src/$(am__dirstamp)
src/spawn.$(OBJEXT): src/$(am__dirstamp)
src/ssl.$(OBJEXT): src/$(am__dirstamp)
src/state.$(OBJEXT): src/$(am__dirstamp)
src/status.$(OBJEXT): src/$(am__dirstamp)
src/util.$(OBJEXT): src/$(am__dirstamp)
src/validate.$(OBJEXT): src/$(am__dirstamp)
src/xmalloc.$(OBJEXT): src/$(am__dirstamp)
src/xml.$(OBJEXT): src/$(am__dirstamp)
src/http/$(am__dirstamp):
	@$(MKDIR_P) src/http
	@: > src/http/$(am__dirstamp)
src/http/base64.$(OBJEXT): src/http/$(am__dirstamp)
src/http/cervlet.$(OBJEXT): src/http/$(am__dirstamp)
src/http/engine.$(OBJEXT): src/http/$(am__dirstamp)
src/http/processor.$(OBJEXT): src/http/$(am__dirstamp)
src/protocols/$(am__dirstamp):
	@$(MKDIR_P) src/protocols
	@: > src/protocols/$(am__dirstamp)
src/protocols/apache_status.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/clamav.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/default.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/dns.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/dwp.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/ftp.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/generic.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/gps.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/http.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/imap.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/ldap2.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/ldap3.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/lmtp.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/memcache.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/mysql.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/nntp.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/ntp3.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/pgsql.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/pop.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/postfix_policy.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/protocol.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/radius.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/rdate.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/rsync.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/sip.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/smtp.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/ssh.$(OBJEXT): src/protocols/$(am__dirstamp)
src/protocols/tns.$(OBJEXT): src/protocols/$(am__dirstamp)
src/device/$(am__dirstamp):
	@$(MKDIR_P) src/device
	@: > src/device/$(am__dirstamp)
src/device/device_common.$(OBJEXT): src/device/$(am__dirstamp)
src/device/sysdep_DARWIN.$(OBJEXT): src/device/$(am__dirstamp)
src/process/$(am__dirstamp):
	@$(MKDIR_P) src/process
	@: > src/process/$(am__dirstamp)
src/process/process_common.$(OBJEXT): src/process/$(am__dirstamp)
src/process/sysdep_DARWIN.$(OBJEXT): src/process/$(am__dirstamp)
monit$(EXEEXT): $(monit_OBJECTS) $(monit_DEPENDENCIES) 
	@rm -f monit$(EXEEXT)
	$(monit_LINK) $(monit_OBJECTS) $(monit_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/alert.$(OBJEXT)
	-rm -f src/collector.$(OBJEXT)
	-rm -f src/control.$(OBJEXT)
	-rm -f src/daemonize.$(OBJEXT)
	-rm -f src/device/device_common.$(OBJEXT)
	-rm -f src/device/sysdep_DARWIN.$(OBJEXT)
	-rm -f src/env.$(OBJEXT)
	-rm -f src/event.$(OBJEXT)
	-rm -f src/file.$(OBJEXT)
	-rm -f src/gc.$(OBJEXT)
	-rm -f src/http.$(OBJEXT)
	-rm -f src/http/base64.$(OBJEXT)
	-rm -f src/http/cervlet.$(OBJEXT)
	-rm -f src/http/engine.$(OBJEXT)
	-rm -f src/http/processor.$(OBJEXT)
	-rm -f src/lex.yy.$(OBJEXT)
	-rm -f src/log.$(OBJEXT)
	-rm -f src/md5.$(OBJEXT)
	-rm -f src/monit.$(OBJEXT)
	-rm -f src/net.$(OBJEXT)
	-rm -f src/process.$(OBJEXT)
	-rm -f src/process/process_common.$(OBJEXT)
	-rm -f src/process/sysdep_DARWIN.$(OBJEXT)
	-rm -f src/protocols/apache_status.$(OBJEXT)
	-rm -f src/protocols/clamav.$(OBJEXT)
	-rm -f src/protocols/default.$(OBJEXT)
	-rm -f src/protocols/dns.$(OBJEXT)
	-rm -f src/protocols/dwp.$(OBJEXT)
	-rm -f src/protocols/ftp.$(OBJEXT)
	-rm -f src/protocols/generic.$(OBJEXT)
	-rm -f src/protocols/gps.$(OBJEXT)
	-rm -f src/protocols/http.$(OBJEXT)
	-rm -f src/protocols/imap.$(OBJEXT)
	-rm -f src/protocols/ldap2.$(OBJEXT)
	-rm -f src/protocols/ldap3.$(OBJEXT)
	-rm -f src/protocols/lmtp.$(OBJEXT)
	-rm -f src/protocols/memcache.$(OBJEXT)
	-rm -f src/protocols/mysql.$(OBJEXT)
	-rm -f src/protocols/nntp.$(OBJEXT)
	-rm -f src/protocols/ntp3.$(OBJEXT)
	-rm -f src/protocols/pgsql.$(OBJEXT)
	-rm -f src/protocols/pop.$(OBJEXT)
	-rm -f src/protocols/postfix_policy.$(OBJEXT)
	-rm -f src/protocols/protocol.$(OBJEXT)
	-rm -f src/protocols/radius.$(OBJEXT)
	-rm -f src/protocols/rdate.$(OBJEXT)
	-rm -f src/protocols/rsync.$(OBJEXT)
	-rm -f src/protocols/sip.$(OBJEXT)
	-rm -f src/protocols/smtp.$(OBJEXT)
	-rm -f src/protocols/ssh.$(OBJEXT)
	-rm -f src/protocols/tns.$(OBJEXT)
	-rm -f src/sendmail.$(OBJEXT)
	-rm -f src/sha.$(OBJEXT)
	-rm -f src/signal.$(OBJEXT)
	-rm -f src/socket.$(OBJEXT)
	-rm -f src/spawn.$(OBJEXT)
	-rm -f src/ssl.$(OBJEXT)
	-rm -f src/state.$(OBJEXT)
	-rm -f src/status.$(OBJEXT)
	-rm -f src/util.$(OBJEXT)
	-rm -f src/validate.$(OBJEXT)
	-rm -f src/xmalloc.$(OBJEXT)
	-rm -f src/xml.$(OBJEXT)
	-rm -f src/y.tab.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

.c.o:
	$(COMPILE) -c -o $@ $<

.c.obj:
	$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(LTCOMPILE) -c -o $@ $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
install-man1: $(man1_MANS) $(man_MANS)
	@$(NORMAL_INSTALL)
	test -z "$(man1dir)" || $(MKDIR_P) "$(DESTDIR)$(man1dir)"
	@list='$(man1_MANS) $(dist_man1_MANS) $(nodist_man1_MANS)'; \
	l2='$(man_MANS) $(dist_man_MANS) $(nodist_man_MANS)'; \
	for i in $$l2; do \
	  case "$$i" in \
	    *.1*) list="$$list $$i" ;; \
	  esac; \
	done; \
	for i in $$list; do \
	  if test -f $(srcdir)/$$i; then file=$(srcdir)/$$i; \
	  else file=$$i; fi; \
	  ext=`echo $$i | sed -e 's/^.*\\.//'`; \
	  case "$$ext" in \
	    1*) ;; \
	    *) ext='1' ;; \
	  esac; \
	  inst=`echo $$i | sed -e 's/\\.[0-9a-z]*$$//'`; \
	  inst=`echo $$inst | sed -e 's/^.*\///'`; \
	  inst=`echo $$inst | sed '$(transform)'`.$$ext; \
	  echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
	  $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst"; \
	done
uninstall-man1:
	@$(NORMAL_UNINSTALL)
	@list='$(man1_MANS) $(dist_man1_MANS) $(nodist_man1_MANS)'; \
	l2='$(man_MANS) $(dist_man_MANS) $(nodist_man_MANS)'; \
	for i in $$l2; do \
	  case "$$i" in \
	    *.1*) list="$$list $$i" ;; \
	  esac; \
	done; \
	for i in $$list; do \
	  ext=`echo $$i | sed -e 's/^.*\\.//'`; \
	  case "$$ext" in \
	    1*) ;; \
	    *) ext='1' ;; \
	  esac; \
	  inst=`echo $$i | sed -e 's/\\.[0-9a-z]*$$//'`; \
	  inst=`echo $$inst | sed -e 's/^.*\///'`; \
	  inst=`echo $$inst | sed '$(transform)'`.$$ext; \
	  echo " rm -f '$(DESTDIR)$(man1dir)/$$inst'"; \
	  rm -f "$(DESTDIR)$(man1dir)/$$inst"; \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d $(distdir) || mkdir $(distdir)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) \
	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
	  dist-hook
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) check-am
all-am: Makefile $(PROGRAMS) $(MANS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-rm -f src/$(am__dirstamp)
	-rm -f src/device/$(am__dirstamp)
	-rm -f src/http/$(am__dirstamp)
	-rm -f src/process/$(am__dirstamp)
	-rm -f src/protocols/$(am__dirstamp)
	-test -z "$(DISTCLEANFILES)" || rm -f $(DISTCLEANFILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libtool clean-local \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-local distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

info: info-am

info-am:

install-data-am: install-man

install-dvi: install-dvi-am

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-info: install-info-am

install-man: install-man1

install-pdf: install-pdf-am

install-ps: install-ps-am

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-man

uninstall-man: uninstall-man1

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic clean-libtool clean-local \
	ctags dist dist-all dist-bzip2 dist-gzip dist-hook dist-shar \
	dist-tarZ dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-libtool \
	distclean-local distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-man1 install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-binPROGRAMS \
	uninstall-man uninstall-man1


# -------
# Targets
# -------

dist-hook::
	-rm -rf `find $(distdir) -name "._*"`
	-rm -rf `find $(distdir) -name ".DS_Store"`
	-rm -rf `find $(distdir) -name ".libs"`
	-rm -rf `find $(distdir) -name ".svn"`
	-rm -f $(distdir)/src/config.h $(distdir)/src/stamp-* 
	-perl -pi -e 's/^Version: .*/Version: '$(VERSION)'/' $(distdir)/contrib/packages/redhat/monit.spec
	-chmod 600 monitrc

clean-local:
	-rm -f `find . -name "*.o" -o -name "*.lo" -o -name "*.loT" -o -name "*~"`

distclean-local:
	-rm -rf autom4te.cache/ \
		src/y.output \
		monit-[0-9].*tar.gz
	-rm -rf lib include

cleanall: clean distclean
	-rm -f Makefile.in configure aclocal.m4 autom4te.cache src/config.h.in monit.1 config/config.*
	-rm -rf m4

monit.1: doc/monit.pod
	$(POD2MAN) $(POD2MANFLAGS) $< > $@
	-rm -f pod2*

# -------------
# Grammar rules
# -------------

src/y.tab.c src/tokens.h : src/p.y
	$(YACC) $(YACCFLAGS) $< -o src/y.tab.c
	echo "#include <config.h>" > src/.y.tab.c
	cat src/y.tab.c >> src/.y.tab.c
	-mv src/.y.tab.c src/y.tab.c
	-mv src/y.tab.h src/tokens.h

src/lex.yy.c: src/l.l
	$(FLEX) $(FLEXFLAGS) -o $@ $< 
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
